version: '3.1'

services:
  frontend:
    container_name: container_front_end
    image: frontend
    depends_on:
      - backend
    restart: always
    build:
      dockerfile: ./frontend/Dockerfile
    networks:
      - costs
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app

  backend:
    container_name: container_back_end
    image: backend
    depends_on:
      - db
    restart: always
    build: 
      dockerfile: ./backend/Dockerfile
    networks:
      - costs
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app

  db:
    container_name: container_db
    image: database
    restart: always
    build: 
      dockerfile: ./db/Dockerfile
    networks:
      - costs
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql

  phpmyadmin: 
    container_name: container_phpmyadmin
    image: phpmyamdin_db
    depends_on:
      - db
    restart: always
    build: 
      dockerfile: ./db/phpmyadmin/Dockerfile
    networks:
      - costs
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: chadmin2020

volumes:
  database:

networks:
  costs:
    driver: bridge

#secrets:
 
#configs:
