version: '3.3'

services:
  db:
    image: banco_de_dados
    restart: always
    networks:
      - costs
    ports:
      - "3306:3306"

  phpmyadmin: 
    depends_on:
      - db
    image: phpmyamdin_db
    restart: always
    networks:
      - costs
    ports:
      - "8888:80"


#volumes:

networks:
  costs:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.3/80
        - gateway: 172.19.0.3
    
    
#secrets:
 
#configs:
